// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xieazmtvtlvexadbzoni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZWF6bXR2dGx2ZXhhZGJ6b25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDg2NTYsImV4cCI6MjA2MDA4NDY1Nn0.ikz-UI5uNJ8rZFHLAvPkxRmXtUDm8TVm_HNbBqD97v0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);